language: go

go:
  - 1.16

go_import_path: github.com/turbonomic/turbo-api

before_install:
  - go get -v github.com/mattn/goveralls

script:
  - make fmtcheck
  - $HOME/gopath/bin/goveralls -v -race -service=travis-ci -ignore="example/*"

